In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv")

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Sección nueva

In [ ]:
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City"])
pop = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["Population"])
cities.tail(10)
pop.tail(10)

     Population
591       11949
592        4114
593       16755
594       16325
595       16905
596       10024
597        5768
598       16679
599       24800
600       13000

In [ ]:
pop.tail()

     Population
596       10024
597        5768
598       16679
599       24800
600       13000

In [ ]:
cities.head(30)

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
5        La Paloma
6            Tutup
7          Ondores
8          Heredia
9             Gaio
10             Ise
11          Volovo
12          Caujul
13      Kutloanong
14        Kobuleti
15          Senlis
16          Wufeng
17          Picton
18     Johor Bahru
19      Fort Worth
20      Santa Cruz
21    Lope de Vega
22          Maubin
23      El Crucero
24           Itzer
25            Erqu
26   Los Cerrillos
27           Uptar
28    Ponta do Sol
29  Boca de Uchire

In [ ]:
pop.head(n = 8)

   Population
0       21722
1        5629
2        5679
3       10085
4       23421
5       22154
6       11558
7       13288

In [ ]:
cities.count()

City    601
dtype: int64

In [ ]:
pop.count()

Population    601
dtype: int64

In [ ]:
cities.describe()

               City
count           601
unique          578
top     San Antonio
freq              4

In [ ]:
pop.describe()

         Population
count    601.000000
mean   13932.415973
std     6765.873291
min     2528.000000
25%     7801.000000
50%    13966.000000
75%    19752.000000
max    38745.000000

In [ ]:
#cities.sort_values()
cities.sort_values(by = ["City"], ascending = True )

              City
581          Abuja
66          Aizhai
472          Aketi
212       Alarobia
467       Alcoutim
..             ...
386  Zhongshangang
69   Zhongshangang
427      Zhongxing
538       Zhuoshui
362           Zliv

[601 rows x 1 columns]

In [ ]:
cities.sort_values(by = ["City"], ascending = False).head()

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang

In [ ]:
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City"])
cities
cities.sort_values(by = ["City"], ascending = False, inplace = True)
cities

              City
362           Zliv
538       Zhuoshui
427      Zhongxing
386  Zhongshangang
69   Zhongshangang
..             ...
467       Alcoutim
212       Alarobia
472          Aketi
66          Aizhai
581          Abuja

[601 rows x 1 columns]

In [ ]:
cities.sort_index(inplace=True)
cities

              City
0           Kajuru
1             Leon
2              Osh
3    Shumikhinskiy
4         Bundoran
..             ...
596        Lobitos
597         Bremen
598         Harare
599          Lagos
600         Oshawa

[601 rows x 1 columns]

In [ ]:
#cities
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv")
cities.sort_index(ascending = False, inplace = True)
cities

              City     Country  Population
600         Oshawa      Canada       13000
599          Lagos     Nigeria       24800
598         Harare    Zimbabwe       16679
597         Bremen     Germany        5768
596        Lobitos        Peru       10024
..             ...         ...         ...
4         Bundoran     Ireland       23421
3    Shumikhinskiy      Russia       10085
2              Osh  kyrgyzstan        5679
1             Leon       Spain        5629
0           Kajuru    Botswana       21722

[601 rows x 3 columns]

In [ ]:
print(cities)

              City     Country  Population
600         Oshawa      Canada       13000
599          Lagos     Nigeria       24800
598         Harare    Zimbabwe       16679
597         Bremen     Germany        5768
596        Lobitos        Peru       10024
..             ...         ...         ...
4         Bundoran     Ireland       23421
3    Shumikhinskiy      Russia       10085
2              Osh  kyrgyzstan        5679
1             Leon       Spain        5629
0           Kajuru    Botswana       21722

[601 rows x 3 columns]

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv")
data

              City     Country  Population
0           Kajuru    Botswana       21722
1             Leon       Spain        5629
2              Osh  kyrgyzstan        5679
3    Shumikhinskiy      Russia       10085
4         Bundoran     Ireland       23421
..             ...         ...         ...
596        Lobitos        Peru       10024
597         Bremen     Germany        5768
598         Harare    Zimbabwe       16679
599          Lagos     Nigeria       24800
600         Oshawa      Canada       13000

[601 rows x 3 columns]

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", index_col = ["City"])
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City"], index_col = ["City"])
#data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv")
data.head()

Empty DataFrame
Columns: []
Index: [Kajuru, Leon, Osh, Shumikhinskiy, Bundoran]

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City"])
city = data["City"]
city.get(3)

'Shumikhinskiy'

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv")
poblacion = data["Population"]
print(poblacion)
#cities.head()

0      21722
1       5629
2       5679
3      10085
4      23421
       ...
596    10024
597     5768
598    16679
599    24800
600    13000
Name: Population, Length: 601, dtype: int64

In [ ]:
cities = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols=["City"], index_col=["City"])
cities.iloc[7]

Series([], Name: Ondores, dtype: float64)

In [ ]:
cities[10:20]

10            Ise
11         Volovo
12         Caujul
13     Kutloanong
14       Kobuleti
15         Senlis
16         Wufeng
17         Picton
18    Johor Bahru
19     Fort Worth
Name: City, dtype: object

In [ ]:
cities[:15]

0            Kajuru
1              Leon
2               Osh
3     Shumikhinskiy
4          Bundoran
5         La Paloma
6             Tutup
7           Ondores
8           Heredia
9              Gaio
10              Ise
11           Volovo
12           Caujul
13       Kutloanong
14         Kobuleti
Name: City, dtype: object

In [ ]:
cities[:26:2]

0          Kajuru
2             Osh
4        Bundoran
6           Tutup
8         Heredia
10            Ise
12         Caujul
14       Kobuleti
16         Wufeng
18    Johor Bahru
20     Santa Cruz
22         Maubin
24          Itzer
Name: City, dtype: object

In [ ]:
cities[-10:]

591    Bagumbayan
592      Tuanshan
593       Sapporo
594    Cocachacra
595        Kurjan
596       Lobitos
597        Bremen
598        Harare
599         Lagos
600        Oshawa
Name: City, dtype: object

In [ ]:
cities[[3, 5, 7]]
#cities.sort_values()

3    Shumikhinskiy
5        La Paloma
7          Ondores
Name: City, dtype: object

In [ ]:
#Retrieving data from a series by index label:

#city = pd.read_csv("Cities.csv", usecols = ["City", "Country"])
city = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City", "Country"], index_col = "City")
city = city["Country"]
city

City
Kajuru             Botswana
Leon                  Spain
Osh              kyrgyzstan
Shumikhinskiy        Russia
Bundoran            Ireland
                    ...
Lobitos                Peru
Bremen              Germany
Harare             Zimbabwe
Lagos               Nigeria
Oshawa               Canada
Name: Country, Length: 601, dtype: object

In [ ]:
city[0]

<ipython-input-29-8f5a1a4338dc>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  city[0]

'Botswana'

In [ ]:
city["Lobitos"]

City
Lobitos    Peru
Lobitos    Peru
Name: Country, dtype: object

In [ ]:
city["Kajuru"]

'Botswana'

In [ ]:
city.sort_index(inplace = True, ascending = True)
city

City
Abuja                                     Nigeria
Aizhai                                      China
Aketi            Democratic Republic of the Congo
Alarobia                               Madagascar
Alcoutim                                 Portugal
                               ...
Zhongshangang                               China
Zhongshangang                               China
Zhongxing                                   China
Zhuoshui                                    China
Zliv                               Czech Republic
Name: Country, Length: 601, dtype: object

In [ ]:
city["Abuja":"Bremen"]

City
Abuja                                 Nigeria
Aizhai                                  China
Aketi        Democratic Republic of the Congo
Alarobia                           Madagascar
Alcoutim                             Portugal
                           ...
Bolgar                                 Russia
Bomomani                            Indonesia
Bonavista                              Canada
Bradag                              Indonesia
Bremen                                Germany
Name: Country, Length: 84, dtype: object

In [ ]:
city[:"Bremen"]

City
Abuja                                 Nigeria
Aizhai                                  China
Aketi        Democratic Republic of the Congo
Alarobia                           Madagascar
Alcoutim                             Portugal
                           ...
Bolgar                                 Russia
Bomomani                            Indonesia
Bonavista                              Canada
Bradag                              Indonesia
Bremen                                Germany
Name: Country, Length: 84, dtype: object

In [ ]:
city[["Bolgar", "Abuja", "Osh"]]

City
Bolgar        Russia
Abuja        Nigeria
Osh       kyrgyzstan
Name: Country, dtype: object

In [ ]:
city.head(10)

City
Abuja                                      Nigeria
Aizhai                                       China
Aketi             Democratic Republic of the Congo
Alarobia                                Madagascar
Alcoutim                                  Portugal
Alis                                          Peru
Alvaro Obregon                              Mexico
Amargosa                                    Brazil
Amuru                                       Uganda
Anan                                         Japan
Name: Country, dtype: object

In [ ]:
city["Abuja": "Anan": 2]

City
Abuja                                      Nigeria
Aketi             Democratic Republic of the Congo
Alcoutim                                  Portugal
Alvaro Obregon                              Mexico
Amuru                                       Uganda
Name: Country, dtype: object

In [ ]:
#data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City", "Country"], index_col = "City")
data = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Cities.csv", usecols = ["City", "Country"])
data.sort_index(inplace = True)
data

              City     Country
0           Kajuru    Botswana
1             Leon       Spain
2              Osh  kyrgyzstan
3    Shumikhinskiy      Russia
4         Bundoran     Ireland
..             ...         ...
596        Lobitos        Peru
597         Bremen     Germany
598         Harare    Zimbabwe
599          Lagos     Nigeria
600         Oshawa      Canada

[601 rows x 2 columns]

In [ ]:
city = data["City"]
city

0             Kajuru
1               Leon
2                Osh
3      Shumikhinskiy
4           Bundoran
           ...
596          Lobitos
597           Bremen
598           Harare
599            Lagos
600           Oshawa
Name: City, Length: 601, dtype: object

In [ ]:
city.get(3)

'Shumikhinskiy'

In [ ]:
city.get([1, 5])
city

0             Kajuru
1               Leon
2                Osh
3      Shumikhinskiy
4           Bundoran
           ...
596          Lobitos
597           Bremen
598           Harare
599            Lagos
600           Oshawa
Name: City, Length: 601, dtype: object

In [ ]:
#city.get(["Aizahai", "Alis"])
print(city.get(["Aizahai", "Alis"]))

None

In [ ]:
print(city.get(780))

None

In [ ]:
city.dtype      #To veriry that cuty is an object 'o'

dtype('O')

In [ ]:
city.values

array(['Kajuru', 'Leon', 'Osh', 'Shumikhinskiy', 'Bundoran', 'La Paloma',
       'Tutup', 'Ondores', 'Heredia', 'Gaio', 'Ise', 'Volovo', 'Caujul',
       'Kutloanong', 'Kobuleti', 'Senlis', 'Wufeng', 'Picton',
       'Johor Bahru', 'Fort Worth', 'Santa Cruz', 'Lope de Vega',
       'Maubin', 'El Crucero', 'Itzer', 'Erqu', 'Los Cerrillos', 'Uptar',
       'Ponta do Sol', 'Boca de Uchire', 'Pagsanahan Norte',
       'Khlong Luang', 'Dazhipo', 'Berezovo', 'Mahajanga', 'Hexi', 'Tuwa',
       'Bawshar', 'Sundbyberg', 'Lattes', 'Ciyun', 'Bureng', 'Dahewan',
       'Lobitos', 'Esso', 'Heshang', 'Luknovo', 'Ancahuasi',
       'Ciudad Nueva', 'Claveria', 'Tiexi', 'Lisieux', 'Rennes', 'Ivoti',
       'Santa Marta', 'Utkivka', 'Gombang', 'Panay', 'Saribudolok',
       'Pervomayskiy', 'Pereiras', 'Fika', 'Sucre', 'Hengdaohezi',
       'Sinegorskiy', 'Strazhitsa', 'Aizhai', 'Marco', 'Donskoye',
       'Zhongshangang', 'Colomi', 'Sabbah', 'San Carlos de Bariloche',
       'Bagenalstown', 'Bolgar', 'Saint-Louis', 'Cawalo', 'Corroios',
       'Khueang Nai', 'Trondheim', 'Sicamous', 'Hayan Hudong',
       'Arroio do Meio', 'Giade', 'Catarman', 'Carapelhos', 'Bojano',
       'Kapatagan', 'Lobamba', 'Laranjal Paulista', 'Bela Vista',
       'Buenavista', 'Cikubang', 'Ban Tak', 'Kinamayan', 'Salima',
       'Tiniguiban', 'Essen', 'Emmen', 'San Antonio', 'Trat', 'Manaquiri',
       'Chivor', 'Ubay', 'Chartres', 'Heshi', 'Sambirobyong',
       'Tekik Wetan', 'Nashville', 'Cabangan', 'Guacara',
       'Si Satchanalai', 'San Antonio', 'Shuakhevi', 'Dzyatlava',
       'Oakville', 'Lanpelan', 'Arganil', 'Marevo', 'Nikita', 'Bhamdoun',
       'Oliveiras', 'Vreshtas', 'Itacoatiara', 'Noeltoko', 'Gadang',
       'Kyzyl-Kyya', 'Waitakere', 'Hirosaki', 'Providencia', 'Houilles',
       'Pekuncen', 'Sumberkenanga', 'Miaoli', 'Uppsala', 'Pilcomay',
       'Chrast', 'Sarana', 'Mogok', 'Beidu', 'Lanjaghbyur', 'Johanneshov',
       'Fresnes', 'Krajan Nglinggis', 'Fershampenuaz', 'Andrushivka',
       'Ban Rangsit', 'Rennes', 'Kastav', 'Panunggangan', 'Solotcha',
       'Sezemice', 'Bailizhou', 'Obando', 'Ban Pong', 'El Mirador',
       'Tarui', 'Kliteh', 'Surazh', 'Plumtree', 'Avignon', 'Okcheon',
       'Kapchorwa', 'Umanggudang', 'Cibeureum', 'Prochnookopskaya',
       'Barentu', 'Nong Ki', 'Maketu', 'Gunungputri', 'Mopti', 'Challans',
       'Prince Albert', 'Effium', 'Nkhotakota', 'Nikita', 'Bendorubuh',
       'Plettenberg Bay', 'Bulalacao', 'Anhua Daying', 'Sam Chuk',
       'Bulri', 'Sexmoan', 'Santa Cruz', 'Bagacay', 'Haapsalu', 'Kwekwe',
       'Tingsiqiao', 'Lajedo', 'Sembung', 'Bulungu', 'Arnhem', 'Cruz',
       'Sidi Amar', 'Gucheng', 'Kungshamn', 'Santana do Ipanema',
       'Dumalinao', 'Sovetskoye', 'Roa', 'Dingtou', 'Sukowiryo', 'Gaoshi',
       'Magatos', 'Likino-Dulevo', 'Lhokkruet', 'Roermond', 'Longos',
       'Isfahan', 'Madrid', 'Banjar Kertasari', 'Klana', 'Alarobia',
       'Cabanilla', 'Lusaka', 'Choibalsan', 'Pandat', 'Cibeureum',
       'Hampang', 'Dalupirip', 'Binulasan', 'Inta', 'Palu', 'La Mesa',
       'Inashiki', 'Stockholm', 'Campos Novos', 'Reserva', 'Arzakan',
       'Sintansin', 'Norberg', 'Santa Cruz', 'Malabang', 'Sagana',
       'Firovo', 'Tercena', 'Seixezelo', 'Esposende', 'Bo Kluea',
       'Alvaro Obregon', 'Sammatti', 'Sainte-Agathe-des-Monts',
       'Kerep Wetan', 'Kimito', 'Bradag', 'Guadalupe Victoria',
       'Manis Mekarwangi', 'Floridablanca', 'Galamares', 'Amuru', 'Sima',
       'Buluh Kasap', 'Limbi', 'Alis', 'Tubod', 'Birendranagar',
       'Cristalina', 'Ayolas', 'Changping', 'Kose', 'Ciseureuheun',
       'Gaopu', 'Temuji', 'El Puerto', 'Eira Nova', 'Panguipulli',
       'Isidro Fabela', 'Narbonne', 'Mandalasari', 'La Breita', 'Chuanxi',
       'Langres', 'San Juan Ixcoy', 'Tvrdonice', 'Argivai',
       'Kuala Lumpur', 'Zaozerne', 'Deqing', 'Arras', 'Bofuer',
       'El Carmen', 'Kuala Lumpur', 'Kawangohari', 'Bangko', 'Tuoshi',
       'Caotang', 'Chuanpu', 'Butungan', 'Zhatay', 'Guacara', 'Dindima',
       'Banjarjo', 'Antabamba', 'Moro', 'La Esperanza', 'Bayonne',
       'Dukla', 'Open Stage', 'Dorp Tera Kora', 'Umbanyar', 'Harian',
       'Pak Phli', 'Shreveport', 'Proletarskiy', 'El Progreso',
       'Sukamenak', 'Charikar', 'Sukamantri Satu', 'Boca Suno', 'Molina',
       'Magalalag', 'Banakaja', 'Helsingborg', 'Hecun', 'Morden',
       'Osapsio', 'Webuye', 'Rizal', 'Cibanten', 'Chornoliztsi',
       'Sabana Grande de Palenque', 'Citalahab', 'Pantai Ceuremen',
       'Gongju', 'Bonavista', 'Richmond', 'Denver', 'Faraulep',
       'Maswarah', 'Arauca', 'Zhiletovo', 'Rosmalen', 'Segbwema',
       'Gayamdesa', 'Mahaplag', 'Lais', 'Dungon', 'Jungkat Selatan',
       'Likhobory', 'Tungol', 'Pancur', 'Sarirejo Satu',
       'Kliwon Cibingbin', 'Heliconia', 'Kyjov', 'Gaoshi', 'Frei',
       'Kotel', 'Guxi', 'Semambung', 'Ifanadiana', 'Malakwal City',
       'Pengilon', 'Baitoa', 'Werangere', 'Boden', 'Tiyuguan',
       'Staromyshastovskaya', 'Aranguren', 'Rakitnoye', 'Chuandao',
       'Campo Maior', 'Zliv', 'Dahua', 'Machala', 'Suleja', 'Letpandan',
       'Kirzhach', 'Heyou', 'Daduchuan', 'Hikkaduwa', 'Arzakan', 'Baleal',
       'Simpangpasir', 'Hailang', 'Bulls', 'Cibenda', 'Inglewood',
       'Cimo de Vila', 'Changbai', 'Dalamdesa Kalapadua', 'Nay Pyi Taw',
       'Rosice', 'Tras Cerros', 'Balatun', 'Nong Khai', 'Zhongshangang',
       'Bairros', 'Fatualam', 'Bomomani', 'Kanye', 'San Antonio',
       'Nantes', 'Bitobe', 'Drawsko Pomorskie', 'Majagual', 'El Cortezo',
       'Solnechnyy', 'Isheyevka', 'Cikeusal', 'Refojos de Riba de Ave',
       'Cunha', 'Mayskiy', 'Anchang', 'Schroeder', 'Nelipyno', 'Deje',
       'Gaplokan', 'Ar Ruways', 'Simpangpasir', 'Toronto', 'Ponta do Sol',
       'Ijebu-Ife', 'Telnice', 'Baihe', 'Zhangzhu', 'Guxi', 'Libode',
       'Livadiya', 'Pryamitsyno', 'Tigbinan', 'Rozhdestveno', 'Palmito',
       'Zalanga', 'Buin', 'Oliveira de Frades', 'Amargosa', 'Zhongxing',
       'Zeist', 'Salfīt', 'Khodzha-Maston', 'Dordrecht', 'Casillas',
       'Orsha', 'Mastung', 'Pemzashen', 'Chenqing', 'Daping', 'Hanting',
       'Mogapi', 'Wenquan', 'San Antonio', 'Biting', 'Seshcha', 'Avignon',
       'Suisan', 'Pancur', 'Houston', 'Roissy Charles-de-Gaulle',
       'Tokonou', 'Karanganyar', 'Kuchurhan', 'Buldon', 'Irving',
       'Anmore', 'Beijie', 'Vahdat', 'Toledo', 'Utsjoki', 'Sekirnik',
       'Bitkine', 'Kut Chap', 'Baiheshan', 'Gaoliban', 'Frederiksberg',
       'Fabianki', 'Banjar Kubu', 'Alcoutim', 'Lucma', 'Catbalogan',
       'Mori', 'Margacina', 'Aketi', 'Arroio Grande', 'Kajiado',
       'Delaware', 'Sojo', 'Preserje pri Radomljah', 'Samphanthawong',
       'Callahuanca', 'Opatowiec', 'Prochowice', 'Riba de Ave',
       'Likupang', 'Binzhou', 'Maindang', 'Kogota', 'Enhtal', 'Blois',
       'Uptar', 'Bantu', 'Chama', 'Usarin', 'Villa Regina', 'Erdao',
       'Khawr Maksar', 'Kama', 'Riangblolong', 'Barotac Viejo',
       'Lagoa do Itaenga', 'Zaleszany', 'Wujiabao', 'Cardona', 'Ottawa',
       'Mangunjaya', 'Ngangguk', 'Stamboliyski', 'Tilik', 'Lamarosa',
       'Lat Lum Kaeo', 'Idfu', 'Tippi', 'Makarov', 'Sembung',
       'Sremski Karlovci', 'Vanimo', 'Calebasses', 'Lebowakgomo',
       'Bristol', 'Polo', 'Stryszawa', 'Bakung', 'Concepcion', 'Doom',
       'Bilao', 'Soure', 'Duyang', 'Wenquan', 'Bantilan', 'Leuweheq',
       'Lapi', 'Op', 'Hedi', 'Gwangjeok', 'Fox Creek', 'Lama',
       'Rominimbang', 'Haikou', 'Zhuoshui', 'Sambongmulyo', 'Orsha',
       'Jrashen', 'Zhentou', 'Paris 10', 'Kanal', 'Castlepollard', 'Sim',
       'Daejeon', 'Brest', 'Kināna', 'Tomsk', 'Benito Juarez', 'Ghormach',
       'Kanzaki', 'Kuala Terengganu', 'Pensacola', 'Recarei', 'Anan',
       'Landskrona', 'Carusucan', 'Minneapolis', 'Matahuasi', 'Gaosheng',
       'Jolo', 'Harbin', 'Sapiranga', 'Ribas do Rio Pardo', 'Kulotino',
       'San Rafael', 'Cogreg Wetan', 'Kut Rang', 'Orlando', 'Bellavista',
       'Lescar', 'Buseresere', 'Angol', 'Waterloo', 'La Gi', 'Cairo',
       'Saguiaran', 'Lipin Bor', 'Abuja', 'Bantawora', 'Waihai',
       'Zhangcun', 'Plaeng Yao', 'Guja', 'Caijiagang', 'Consuelo',
       'Santa Magdalena', 'Gemblengmulyo', 'Bagumbayan', 'Tuanshan',
       'Sapporo', 'Cocachacra', 'Kurjan', 'Lobitos', 'Bremen', 'Harare',
       'Lagos', 'Oshawa'], dtype=object)

In [ ]:
population = pop
population

NameError: name 'pop' is not defined

In [ ]:
population = pop["Population"]
population

0      21722
1       5629
2       5679
3      10085
4      23421
       ...
596    10024
597     5768
598    16679
599    24800
600    13000
Name: Population, Length: 601, dtype: int64

In [ ]:
population.dtype() ### Revisar por que no funciona

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [ ]:
#pop.values
#population.values
population.describe()

count      601.000000
mean     13932.415973
std       6765.873291
min       2528.000000
25%       7801.000000
50%      13966.000000
75%      19752.000000
max      38745.000000
Name: Population, dtype: float64

In [ ]:
city.index

RangeIndex(start=0, stop=601, step=1)

In [ ]:
population.index

RangeIndex(start=0, stop=601, step=1)

In [ ]:
city.is_unique

False

In [ ]:
population.is_unique

False

In [ ]:
city.ndim

1

In [ ]:
#pop.ndim
population.ndim

0      21722
1       5629
2       5679
3      10085
4      23421
       ...
596    10024
597     5768
598    16679
599    24800
600    13000
Name: Population, Length: 601, dtype: int64

In [ ]:
info.ndim

2